### ISSUE TITLE
5.9 PLZ

### ISSUE THREAD

**Issue by NitroXenon** [Spl3en/LoLClientAPI#1]
Please update patch 5.9. :+1: 
This project is amazing <3

**Comment by Spl3en** [comment]
What API would you want to fix ?
The camera APIs are working fine for me

	Camera position = 500.953369 / 4354.735840
	Camera angle = 180.000000 / 56.000000
	Camera zoom = 0.000000  <-- Not working
	Cursor position = 8.081055 / 4057.168701
	Destination position = 626.910767 / 4541.720215
	Champion position = 625.000000 / 4513.000000
	Champion HP = 0.000000 / 0.000000 <-- Not working
	Champion team = 0 <-- Not working
	Teammates count = 0 <-- Not working
	cursorScreen position = 461 / 792
	Minimap position = 0 / 0 <-- Not working
	Current summonerName = Spl3en
	Current time = 85.9198684692

**Comment by NitroXenon** [comment]
Ok got it. Would test it for 5.9 later.

**Comment by NitroXenon** [comment]
I've found some useful projects but some of them are discontinued. If you feel tired and dont want to maintain this, pls teach us how to search those offsets. 

Thank you for maintaining and working on this project. Everyone can make some useful tool using this API. I appreciate you a lot xD. :+1:

**Comment by Spl3en** [comment]
I'd love to teach you how to find the offsets, but unfortunately that's not something I can explain to you in few lines. 

It requires a basic understanding of reverse engineering, it is not too much complicated but it requires some time to understand the basics.

I've made a tutorial about how to find zoom value easily, using CheatEngine : 
http://www.elitepvpers.com/forum/tutorials/1849328-tut-how-code-your-own-zoomhack-your-games-pictures-detailed.html
I made it 3 years ago, and I was pretty much a begginer, so it's perfect if you don't know much about game hacking. Actually, this tutorial is a bit confusing, because I didn't realize that the zoom value was a `float` not an `integer`.


If you want to learn with more serious materials, I suggest you to learn about assembly, IDA pro, and OllyDBG.
Assembly is the language itself, it is important that you understand basic instructions (`mov`, `push`, `pop` and `call` at least)

For OllyDBG, I suggest you to read those tutorials : http://thelegendofrandom.com/blog/sample-page
You'll learn how to trace an application and execute it step by step.

For IDA Pro, I suggest you to watch the reverse of the game "Capitalism 2" : https://www.youtube.com/watch?v=vb18UVF4a_o (You can find IDA 6.6 + HexRays very easily on internet...)
IDA is really important to learn because you can reconstruct structures efficiently with HexRays. Structures are important for finding offsets.

I'm glad you appreciate this API, I had fun writing it and still have fun maintaining it. I'm working on other projects so I don't really want to spend time fixing APIs that nobody uses (Chat APIs), but if you want me to fix something, just ask.

**Comment by NitroXenon** [comment]
Thanks for the details. You are such a nice man <3

Btw can you fix the chat APIs? I think this APIs have much potential. Using this APIs, I can make in game IRC chat easily. Hope you can fix the chat APIs.

**Comment by Spl3en** [comment]
Haha, I would love to see your IRC chat in LoL, that would be awesome !

The Chat APIs have been fixed : https://github.com/Spl3en/LoLClientAPI/releases

Enjoy :)

**Comment by NitroXenon** [comment]
Wow it works perfectly. Thank you for updating the Chat APIs. Awesome!
